version: "3"
services:

  app:
    build: scrappy_coco
    volumes:
      - code:/code
    ports:
      - "9080:9080"

  telegram:
    build: telegram
    command: "python bot.py"
    depends_on:
      - app

volumes:
  code:
