version: "3"
services:

  app:
    build: scrappy_coco
    # command: "scrapy crawl reddit -o reddit.json -a subreddits=cats;brazil;worldnews"
    volumes:
      - code:/code

  telegram:
    build: telegram
    command: "python bot.py"
    ports:
      - "80:80"

volumes:
  code:
