version: "3"
services:

  app:
    build: scrappy_coco
    volumes:
      - ./scrappy_coco:/code
    ports:
      - "9080:9080"

  telegram:
    build: telegram
    command: "python bot.py"
    volumes:
      - ./telegram:/code
    depends_on:
      - app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
