version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s'
handlers:
  console:
    level: INFO
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    level: DEBUG
    formatter: simple
    class: logging.FileHandler
    filename: 'telegram.log'
loggers:
  telegram.bot:
    level: INFO
    handlers: [console]
root:
  level: DEBUG
  handlers: [console, file]
